%YAML:1.0

# NUMBER OF CAMERAS TO HANDLE

camera_count: 1

# PHYSICAL IDs OF THE CAMERAS

cameras_id: [0]

# MAXIMUM TIME IN ms BETWEEN 2 CONSECUTIVES FRAMES

timeout: 3000

# WIDTH OF THE FRAMES

width: 640

# HEIGHT OF THE FRAMES

height: 480

# FRAMES PER SECOND

fps: 30

# VIDEO SERVER PORT

port: 8550

# COMMANDS SERVER PORT

tcp_port: 8000
