%YAML:1.0

# NUMBER OF CAMERAS TO HANDLE

camera_count: 1

# PHYSICAL IDs OF THE CAMERAS
# The Server WILL segfault if only one of the ID's is incorrect

cameras_id: [0]

# MAXIMUM TIME IN ms BETWEEN 2 FRAMES

timeout: 40

# WIDTH OF THE FRAMES

width: 640

# HEIGHT OF THE FRAMES

height: 480

# FRAMES PER SECOND

fps: 30

# SERVER PORT

port: 8551
